"""Add task fields

Revision ID: 07528deb365a
Revises: 71a9712e7de3
Create Date: 2025-08-30 23:11:38.854863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07528deb365a'
down_revision: Union[str, None] = '71a9712e7de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_tasks', sa.Column('estimated_hours', sa.Float(), nullable=True))
    op.add_column('compliance_tasks', sa.Column('actual_hours', sa.Float(), nullable=True))
    op.add_column('compliance_tasks', sa.Column('completion_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_tasks', 'completion_percentage')
    op.drop_column('compliance_tasks', 'actual_hours')
    op.drop_column('compliance_tasks', 'estimated_hours')
    # ### end Alembic commands ###
