"""Fix jurisdiction requirements column naming conflict

Revision ID: 13749be853d8
Revises: 8d90213f947b
Create Date: 2025-09-11 20:01:13.724493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13749be853d8'
down_revision: Union[str, None] = '8d90213f947b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jurisdictions', sa.Column('requirements_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jurisdictions', 'requirements_data')
    # ### end Alembic commands ###
