"""Add Assistant API support and assessment tracking

Revision ID: 4648a552daa2
Revises: 13749be853d8
Create Date: 2025-09-12 01:30:16.131613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4648a552daa2'
down_revision: Union[str, None] = '13749be853d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
