"""Add plan field to users table

Revision ID: 780d9ddeaa1c
Revises: 07528deb365a
Create Date: 2025-09-02 21:13:01.457212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780d9ddeaa1c'
down_revision: Union[str, None] = '07528deb365a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    plantype = sa.Enum('BASIC', 'PROFESSIONAL', name='plantype')
    plantype.create(op.get_bind())
    
    # Add column with default value
    op.add_column('users', sa.Column('plan', plantype, nullable=False, server_default='BASIC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    
    # Drop enum type
    plantype = sa.Enum('BASIC', 'PROFESSIONAL', name='plantype')
    plantype.drop(op.get_bind())
    # ### end Alembic commands ###
