"""Add extracted_text and extraction_metadata to ComplianceDocument

Revision ID: 7d91fb0ba16b
Revises: 703b1976881c
Create Date: 2025-09-15 18:37:24.329535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d91fb0ba16b'
down_revision: Union[str, None] = '703b1976881c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('compliance_documents', sa.Column('extraction_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_documents', 'extraction_metadata')
    op.drop_column('compliance_documents', 'extracted_text')
    # ### end Alembic commands ###
