"""Add Float import for confidence score

Revision ID: 86a06fdd066c
Revises: 4648a552daa2
Create Date: 2025-09-12 01:44:44.063295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a06fdd066c'
down_revision: Union[str, None] = '4648a552daa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('source_document_name', sa.String(length=255), nullable=True),
    sa.Column('source_document_path', sa.String(length=500), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('total_requirements', sa.Integer(), nullable=False),
    sa.Column('compliant_count', sa.Integer(), nullable=False),
    sa.Column('partial_count', sa.Integer(), nullable=False),
    sa.Column('non_compliant_count', sa.Integer(), nullable=False),
    sa.Column('not_addressed_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('compliance_assessments', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('compliance_assessments', sa.Column('evidence_text', sa.Text(), nullable=True))
    op.add_column('compliance_assessments', sa.Column('recommendation', sa.Text(), nullable=True))
    op.add_column('compliance_assessments', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'compliance_assessments', 'assessment_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('jurisdictions', sa.Column('assistant_id', sa.String(length=100), nullable=True))
    op.add_column('jurisdictions', sa.Column('vector_store_id', sa.String(length=100), nullable=True))
    op.add_column('jurisdictions', sa.Column('source_file_id', sa.String(length=100), nullable=True))
    op.add_column('jurisdictions', sa.Column('assistant_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jurisdictions', 'assistant_created_at')
    op.drop_column('jurisdictions', 'source_file_id')
    op.drop_column('jurisdictions', 'vector_store_id')
    op.drop_column('jurisdictions', 'assistant_id')
    op.drop_constraint(None, 'compliance_assessments', type_='foreignkey')
    op.drop_column('compliance_assessments', 'confidence_score')
    op.drop_column('compliance_assessments', 'recommendation')
    op.drop_column('compliance_assessments', 'evidence_text')
    op.drop_column('compliance_assessments', 'session_id')
    op.drop_table('assessment_sessions')
    # ### end Alembic commands ###
