"""Update compliance models for document management

Revision ID: 8d90213f947b
Revises: ab55413704f9
Create Date: 2025-09-11 17:57:10.907929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d90213f947b'
down_revision: Union[str, None] = 'ab55413704f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('compliance_requirements', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.add_column('compliance_requirements', sa.Column('title', sa.String(length=500), nullable=False))
    op.add_column('compliance_requirements', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('compliance_requirements', sa.Column('section_reference', sa.String(length=100), nullable=True))
    op.add_column('compliance_requirements', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'compliance_requirements', 'compliance_documents', ['source_document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compliance_requirements', type_='foreignkey')
    op.drop_column('compliance_requirements', 'created_at')
    op.drop_column('compliance_requirements', 'section_reference')
    op.drop_column('compliance_requirements', 'page_number')
    op.drop_column('compliance_requirements', 'title')
    op.drop_column('compliance_requirements', 'source_document_id')
    op.drop_table('compliance_documents')
    # ### end Alembic commands ###
