"""Add compliance document management tables

Revision ID: ab55413704f9
Revises: faf2aa18500b
Create Date: 2025-09-11 17:51:01.307792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab55413704f9'
down_revision: Union[str, None] = 'faf2aa18500b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_reports', 'data')
    op.drop_constraint('compliance_requirements_jurisdiction_id_requirement_id_key', 'compliance_requirements', type_='unique')
    op.drop_column('jurisdictions', 'requirements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jurisdictions', sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint('compliance_requirements_jurisdiction_id_requirement_id_key', 'compliance_requirements', ['jurisdiction_id', 'requirement_id'])
    op.add_column('compliance_reports', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
